; SPARK — Master WROOM  (Coordinator / Game-State Engine)
; Board:  ESP32 DevKit V1  (4 MB Flash)

[env:master_wroom]
platform  = espressif32
board     = esp32dev
framework = arduino

board_build.partitions = min_spiffs.csv

monitor_speed = 115200

lib_deps =
    links2004/WebSockets          @ ^2.4.1
    bblanchon/ArduinoJson         @ ^6.21.5
    adafruit/Adafruit BME680 Library    @ ^2.0.4
    adafruit/Adafruit Unified Sensor    @ ^1.1.14
    fastled/FastLED               @ ^3.7.0

build_flags =
    -DNODE_ID=0
    -I../../shared
    -Wall
